apiVersion: apps/v1
kind: Deployment
metadata:
  name: Study-Buddy-AI
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Study-Buddy-AI
  template:
    metadata:
      labels:
        app: Study-Buddy-AI
    spec:
      containers:
      - name: Study-Buddy-AI
        image: sunny2916/studybuddy:latest
        ports:
        - containerPort: 8501
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-api-secret
              key: GROQ_API_KEY
